plugins/vtd/src/osi_ground_truth.hpp
plugins/vtd/src/osi_omni_sensor.hpp
plugins/vtd/src/osi_sensor_component.hpp
plugins/vtd/src/task_control.hpp
plugins/vtd/src/vtd_binding.cpp

Minor improvements. Might be a quick one :-)

vtd: Adjust comments and formatting

---

ui/LICENSE-3RD-PARTY.txt
ui/package.json
ui/scripts/create-license-file.py
ui/src/components/rendering.jsx
ui/yarn.lock

Required changes from Geometry to BufferGeometry.

ui: Update ThreeJS to 0.125.2

---

ui/LICENSE-3RD-PARTY.txt
ui/package.json
ui/yarn.lock

Web-UI works fine with new version.

ui: Update mathjs to 7.5.1

---

models/include/cloe/component/lane_boundary.hpp

We shouldn't leave the values up to chance.

Initialize members of LaneBoundary class

---

plugins/vtd/src/vtd_binding.cpp

Besides additional statistics that were added, the time spent in the VTD binding in every cycle can now be analyzed by looking into the api recording file. Just change your stack file like so:
```
"engine": {
"output": {
"files": {
"api_recording": "data.json.gz"
}
}
}
```

vtd: Add timers for performance analysis

---

plugins/minimator/src/minimator.cpp

Fix inconsistent naming of json keys that leads to errors in the web-ui.

minimator: Fix json api

---

vendor/osi-sensor-1.0.0-vtd2.2/conanfile.py
vendor/osi-sensor-1.0.0-vtd2.2/patches/osmp_vtd_v2.2.patch

* In-source build (`make all`) was broken
* The objects were provided in the wrong coordinate system

Fix osi dummy sensor

---

conanfile.py
engine/conanfile.py
fable/conanfile.py
models/conanfile.py
oak/conanfile.py
plugins/basic/conanfile.py
plugins/gndtruth_extractor/conanfile.py
plugins/noisy_sensor/conanfile.py
plugins/vtd/conanfile.py
runtime/conanfile.py

Unit tests shall be run in an environment that is populated by Conan, s. https://github.com/conan-io/conan/issues/8102#issuecomment-732502869

tooling: Run unit tests in Conan environment

---

engine/conanfile.py
fable/conanfile.py
models/conanfile.py
runtime/conanfile.py
vendor/cpp-netlib/conanfile.py

tooling: Set boost dependency to full package mode

---

.github/workflows/build-api-docs.yaml
.github/workflows/build-cloe.yaml
.github/workflows/build-ui.yaml
.github/workflows/build-user-docs.yaml
ui/yarn.lock

This should resolve the following pull-requests:
- #59 
- #61 
- #62
- #67

ui: Upgrade node dependencies

---

Makefile.setup
cli/cloe_launch/__main__.py
tests/test_engine.bats
tests/test_engine_nop_smoketest_dump_with_vtd.json

WITH_VTD=1 and CONAN_USER_HOME pointing to other directories than /home and /root were not covered by the previous test implementation. Should be fixed now.

engine: Fix system test for dump command

---

NOTICE.md
conanfile.py
docs/index.rst
engine/CMakeLists.txt
engine/conanfile.py
fable/conanfile.py
fable/examples/contacts/conanfile.txt
fable/examples/simple_config/conanfile.txt
runtime/conanfile.py
vendor/incbin/conanfile.py

This pull-request bundles a bunch of commits that need to be merged before we can create an Eclipse release.

Release Preparation Work

---

.editorconfig
Makefile
Makefile.package
README.md
docs/conf.py
docs/develop.rst
docs/develop/makefile-package.rst

This PR fixes some issues with the make tooling.

Improve editable package handling

---

engine/src/simulation.cpp

Fix Cloe state machine for irregular situations to go through Abort and Disconnect.

engine: Fix Cloe state machine

---

.github/CODEOWNERS

Thank you @clssn for your work in this project! This PR removes you from the CODEOWNERS file so you can concentrate better on your current projects.
You are of course welcome any time to become more involved in this project again! :-)

git: Remove @clssn from CODEOWNERS

---

ui/server/Makefile
ui/server/server.js

-moved folder replay_data to /.local/share/cloe to have all cloe related data in the root dir /.local/share/cloe
-removed setTimeout in webserver + introducted some error handling (fixing missing plot file)

fixed wrong dir in Makefile + removed timeout in webserver

---

.github/CODEOWNERS

This has the effect that he will be added by default as a reviewer to any change impacting the `/ui/` directory.

Add Patrick as codeowner of the web UI

---

optional/vtd/contrib/projects/cloe_tests/Databases/Germany.2018
optional/vtd/contrib/projects/cloe_tests/Databases/Germany_2018.opt.osgb
optional/vtd/contrib/projects/cloe_tests/Databases/Germany_2018.xodr
optional/vtd/contrib/projects/cloe_tests/Scenarios/acc-test.xosc
optional/vtd/src/omni_sensor_component.cpp
optional/vtd/src/vtd_binding.cpp
optional/vtd/tests/config_vtd_smoketest_xosc.json
optional/vtd/tests/test_vtd_smoketest_xosc.json

this commit includes:
- modifing vtd_binding.cpp to support reading of xosc xml tags
- adding more roadmark_types to omni_sensor_component.cpp
- adding xosc test case with corresponding xodr and osgb file

VTD: Add support for xosc v1.0

---

optional/vtd/vendor/vtd-2022.3/Dockerfile
optional/vtd/vendor/vtd-2022.3/conanfile.py
optional/vtd/vendor/vtd-2022.3/libdeps_pruned.txt

This PR addresses several changes needed to support ubuntu2004 for vtd dockerization

vtd: Change dockerfile to support ubuntu2004

---

engine/src/stack.cpp
engine/src/stack.hpp
engine/tests/test_engine.bats
engine/tests/test_engine_unavailable_component.json
engine/tests/test_engine_unavailable_controller.json
engine/tests/test_engine_unavailable_simulator.json
fable/include/fable/schema/factory.hpp

The error message provided when a plugin is not found is very hard to understand, especially if there are a lot of plugins loaded. This PR changes that. When a plugin -- be it simulator, controller, or component -- cannot be found, an understandable error message is provided:
```console
$ cloe-engine run tests/test_engine_unavailable_component.json
tests/test_engine_unavailable_component.json: unknown component plugin: misspelled
Note:
Error located in JSON segment at /vehicles/0/components/test_failure:
{
"binding": "misspelled"
}
The plugin referred to by the "binding" field is not available.
The following component plugins are available:
noisy_lane_sensor
noisy_object_sensor
speedometer
If the plugin you are looking for is not in that list, then you need
to get cloe-engine to load the …
```

Better error messages for missing plugins

---

engine/src/coordinator.cpp
engine/src/coordinator.hpp
engine/src/simulation_probe.hpp
engine/src/simulation_state_probe.cpp
plugins/mocks/src/delay_action.hpp
plugins/mocks/src/demo_stuck.cpp
runtime/include/cloe/trigger/delay_action.hpp
tests/test_engine_stuck_controller_delay.json

And also add an example action to the demo_stuck controller.
The test that goes along with it isn't run for performance reasons right now.

Improve probe subcommand
