Makefile.all
Makefile.package
README.md
dist/docker/Dockerfile.alpine
dist/docker/Dockerfile.archlinux
dist/docker/Dockerfile.ubuntu
fable/conanfile.py
models/conanfile.py
plugins/vtd/conanfile.py
runtime/conanfile.py
vendor/cpp-netlib/conanfile.py

This PR does a few things:
1. It makes it easier to override *boost* by being less specific on which versions we need.
2. Refactor `Makefile.all` and `Makefile.package` to let Conan build the requirements by default.
This changes the way we build cloe by default a little, but I think it's for the better:
Before, it would look like something like this:
```bash
make VENDOR_ONLY=1 export
make export
make -f Makefile.package package
```
After this PR:
```bash
make export-vendor export package
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eclipse/cloe/5)

Improve Conan version overriding

---

cli/README.md

Trying to install cloe-launch with pipx in editable mode leads to an error.
This comes from PEP 517, supposedly, and the solution is to remove `pyproject.toml`.
This PR improves documentation around installing cloe-launch.

cli: Document how to use pipx to install cloe-launch

---

Makefile.all
conanfile.py
engine/conanfile.py
plugins/vtd/conanfile.py

An option was added to the `cloe-engine` package that allows to specify a boost version (range). In order to overwrite the boost dependency for all upstream packages, `cloe-engine`'s `build_requirements` dependencies needed to be replaced by [private](https://docs.conan.io/en/latest/reference/conanfile/methods.html#requirements) `requirements`. 
With this change, the same boost version is used for all upstream dependencies:
`conan info  -g graph.out engine/ | grep boost`
`conan info -o boost_version=1.65.1 -g graph.out engine/ | grep boost`
Resolves #20.

tooling: Override boost dependency in cloe-engine

---

vendor/vtd/conanfile.py

If the VTD package contains the OSI plugin, `libopen_simulation_interface.so` shall always be linked to the VTD runtime setup directory.

Link vtd osi library to runtime directory

---

engine/CMakeLists.txt
engine/src/simulation.cpp
engine/src/stack.cpp
engine/src/stack.hpp
engine/src/stack_test.cpp
fable/CMakeLists.txt
fable/include/fable/schema/array.hpp
fable/include/fable/schema/custom.hpp
fable/include/fable/schema/interface.hpp
fable/src/fable/schema/custom_test.cpp
runtime/include/cloe/component.hpp

This PR extends the configuration of vehicle components. Previously, a single input (source) component was supported for each component, which is now extended to multiple input components of different derived type.
Resolves #9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eclipse/cloe/17)

Support fusion components

---

vendor/cpp-netlib/CMakeLists.txt
vendor/cpp-netlib/conanfile.py

It turned out that the previous build recipe lead to incompatible boost versions being used if those were installed as system libraries.

vendor: Fix cpp-netlib package recipe

---

fable/conanfile.py
runtime/conanfile.py

Fable was designed to be an independently usable library for
configuration de/serialization and validation. As a library it should
be as flexible as possible regarding its dependencies. Therefore
the requirement was relaxed to >=6.2.0.
Resolves #50.
A simple `make export-vendor package-auto` was successful, but more thorough compatibility tests may be worthwhile.

fable: Relax version fmt version requirement

---

Makefile
Makefile.all
Makefile.package
engine/conanfile.py
fable/conanfile.py
models/conanfile.py
oak/conanfile.py
plugins/basic/conanfile.py
plugins/gndtruth_extractor/conanfile.py
plugins/minimator/conanfile.py
plugins/mocks/conanfile.py
plugins/noisy_sensor/conanfile.py
plugins/speedometer/conanfile.py
plugins/virtue/conanfile.py
plugins/vtd/conanfile.py
runtime/conanfile.py

This is an alternative implementation for lockfiles that I feel is more flexible and also more easily removed should the need arise.
I have tested it in several different constellations and find it very valuable.
Changelog:
- New: Makefile targets accept argument `LOCKFILE_SOURCE` to specify a profile to build a package to. This is compatible with all relevant make targets, such as `package` and `all`.
- Fixed: Makefile checks that option arguments are 0 or 1, such as `WITH_VTD`. 
- Fixed: Makefile `status` target reflects status of packages as they relate to `cloe` metapackage.

Alternative lockfile implementation

---

optional/vtd/tests/profile_default.py

If no VERSION is explicitly set, use the git describe version tag.

vtd: add git describe to profile_default

---

oak/conanfile.py

force rebuild of oak when a new boost version is required

oak: add boost full_package_mode to oak

---

Dockerfile
Makefile.docker
optional/vtd/Dockerfile
setup.sh.example

This moves clean-up into the `setup.sh` file, which is more robust and keeps the Dockerfile clean. This only works because of the `trap` shell feature / command.

Provide more robust setup.sh.example file

---

engine/tests/test_engine_json_schema.json
models/include/cloe/component/driver_request.hpp
models/include/cloe/component/latlong_actuator.hpp
models/include/cloe/component/vehicle_state_model.hpp
models/include/cloe/utility/geometry.hpp
optional/vtd/CMakeLists.txt
optional/vtd/src/actuator_component.hpp
optional/vtd/src/osi_omni_sensor.cpp
optional/vtd/src/osi_utils.cpp
optional/vtd/src/task_control.hpp
optional/vtd/src/vtd_binding.cpp
optional/vtd/src/vtd_data_conversion_test.cpp
optional/vtd/src/vtd_sensor_components.hpp
optional/vtd/src/vtd_vehicle.hpp
optional/vtd/tests/conanfile_with_vtd-2.2.0.py
optional/vtd/tests/conanfile_with_vtd-2022.3.py
optional/vtd/tests/test_vtd.bats
plugins/basic/src/basic.cpp
plugins/basic/src/basic.hpp

This PR addresses the findings of #66 by adding
* a new component `VehicleStateModel`
* a new interface `VtdVehicleControl` that covers both the `DriverControl` (set by `LatLongActuator`) and the `DynObjectState` (set by `VehicleStateModel`) messages
* a new component `DriverRequest` to give controllers access to driver model information from the simulator
* a simple arbitration logic to the basic controller functions.

Add  vehicle dynamics model support

---

fable/CMakeLists.txt
fable/examples/contacts/Makefile
fable/examples/simple_config/Makefile
fable/examples/simple_config/src/main.cpp
fable/include/fable/confable.hpp
fable/include/fable/schema/boolean.hpp
fable/include/fable/schema/number.hpp
fable/include/fable/schema/number_impl.hpp
fable/include/fable/schema/string.hpp
fable/include/fable/utility/gtest.hpp
fable/src/fable/confable.cpp
fable/src/fable/schema/boolean.cpp
fable/src/fable/schema/number.cpp
fable/src/fable/schema/string.cpp
fable/src/fable/schema/string_test.cpp
fable/test_v2_package/CMakeLists.txt
fable/test_v2_package/NOTE
fable/test_v2_package/conanfile.py

There are these changes to the Fable library:
New:
- Add `String` schema `enum_of` method to specify valid values of string.
- Add `String` schema unit tests to test all features.
- Extend utility header `gtest.hpp` to support `Schema` type where previously only `Confable` type was supported.
Changed:
- Remove include of `fable/schema.hpp` in `fable/confable.hpp`. This allows better compile-time optimization but may require users to include `fable/schema.hpp` themselves.
- Update example projects to use modern CMake commands in Makefile.
- Update Conan test package `test_v2_package` to support `conan create .` outside of test package mode.
Performance:
- Extract String implementation from header.
- Extract Boolean implementation from header.
- Extract Number implementation from header.
If …

Improve performance of Fable and extend String schema

---

Makefile
cli/Makefile

This also changes the name of the target in the cli Makefile from conan-profile to export, to be orthogonal with the other Makefile.

tooling: Export cloe-launch-profile as part of export and package targets

---

optional/vtd/vendor/vtd-api-2.2.0/conanfile.py
optional/vtd/vendor/vtd-api-2022.3/conanfile.py

vtd_api_version was not used before due to missing f string character

vtd: Fix missing f string in conanfiles

---

.readthedocs.yaml

This is required now.
See: https://blog.readthedocs.com/migrate-configuration-v2/

Add ReadTheDocs config

---

ui/src/components/navbar.jsx

small bugfix in the ui where users could not upload a gzip json properly due to wrong assumption in application type
application/x-gzip stands for experimental while application/gzip is the proper type for that.

ui: Add proper file type for gzip upload

---

engine/tests/conanfile_with_server.py
engine/tests/conanfile_without_server.py
engine/tests/test_engine.bats
engine/tests/test_engine_replica_smoketest.bats
optional/vtd/tests/conanfile_with_vtd-2.2.0.py
optional/vtd/tests/conanfile_with_vtd-2022.3.py
optional/vtd/tests/test_vtd.bats
plugins/gndtruth_extractor/tests/conanfile_default.py
plugins/minimator/tests/conanfile_default.py
plugins/minimator/tests/test_minimator.bats
plugins/virtue/tests/conanfile_default.py
plugins/virtue/tests/test_virtue.bats
tests/conanfile_default.py
tests/conanfile_with_boost_1.78.py
tests/test_all_plugin_usages.bats

Fix:
- Test configurations depend on any compatible version of `cloe-launch-profile`
- Don't fail test when `*.so` glob does not match anything
Refactor:
- Nest `'` quotes inside `"` in test definitions instead of nesting `"` inside `"`.
Yes, it works, but it makes working with it more difficult than it needs to be.

Fix and refactor system tests

---

fable/src/fable/schema/number.cpp

As it turns out, specially for char, the following is true:
char != unsigned char
char != signed char
Which is surprising to me. I hope that this is compatible with other compilers, otherwise this change will need some secondary patching.
---
Note: this was originally slated for 0.20.1, but that release got cancelled.

fable: Instantiate missing Number<signed char>

---

fable/CMakeLists.txt
fable/include/fable/schema/confable.hpp
fable/src/fable/schema/map_nested_test.cpp
fable/src/fable/schema/map_test.cpp

fable: Fix critical error using FromConfable as prototype schema

---

engine/src/simulation.cpp
engine/src/simulation_context.hpp

This is required by the UI for properly changing simulation speed.

Add loop event to engine

---

fable/CMakeLists.txt
fable/conanfile.py
fable/src/fable/version.hpp.in
fable/src/fable/version_test.cpp

This allows users to support multiple fable versions at compile-time.
This is separate from `cloe-runtime` in #197 because:
1. Package `fable` is often used where `cloe-runtime` is not needed.
2. Package `fable` will have independent versioning in the future.
This is generated from src/fable/version.hpp.in
See the file for the documentation.

Generate fable/version.hpp header for fable

---

runtime/CMakeLists.txt
runtime/conanfile.py
runtime/src/cloe/version.hpp.in
runtime/src/cloe/version_test.cpp

Depends on #198.
This allows users to support multiple Cloe runtime versions at compile-time.
This is generated from src/runtime/version.hpp.in
See the file for the documentation.

Generate cloe/version.hpp header for cloe-runtime

---

plugins/esmini/src/esmini_osi_sensor.hpp
plugins/esmini/tests/config_esmini_open_loop.json

Patching the `osi3:GroundTruth` data coming from ESMini became obsolete in recent versions, see https://github.com/esmini/esmini/issues/353

esmini fixes

---

osi/CMakeLists.txt
osi/include/cloe/component/osi_sensor.hpp
osi/include/cloe/utility/osi_utils.hpp
osi/src/cloe/component/osi_sensor.cpp

The serialized osi message shall be available through the component interface, such that plugins like the `gndtruth_extractor` can make use of it.

osi: Serialize OsiSensor active state

---

vendor/open-simulation-interface/conanfile.py

Set full_package_mode for Protobuf to consider the case that a consumer recipe might set Protobuf as a shared or static library.
How to reproduce issue:
- Set the following options in your consumer: 'self.options['open-simulation-interface'].shared = True' and
'self.options['protobuf'].shared = True'
- Then upload the packages to artifactory.
- Now change `self.options['protobuf'].shared = False` in your consumer package.
- Try to compile again. Assuming that your Conan configuration has as default `default_package_id_mode = semver_direct_mode' then the first version of OSI produced which links to a Protobuf as shared library is installed in your Conan cache.

vendor/open-simulation-interface: Add full_package_mode

---

.github/dependabot.yml

When the UI is actively developed, then Dependabot is valuable. As it is right now, we don't have capacity to test all the PRs it is making. There are three options:
1. Disable Dependabot for now.
2. Merge PRs and hope for the best.
3. Ignore PRs.
This PR implements option 1.

tooling: Disable dependabot for the UI
